const path = require('path');

/**
 * Modify webpack config generated by snowpack
 * @param {import("webpack").Configuration} config The webpack config generated by snowpack
 */
function modifyWebpackConfig(config) {
  config.entry['use-small'] = path.resolve(__dirname, "build", "dist", "use-small.js")
  console.log(JSON.stringify(config, null, 2));
  return config;
};


module.exports = {
  mount: {
    public: {url: '/', static: true},
    src: {url: '/dist'},
  },
  plugins: [
    '@snowpack/plugin-svelte',
    '@snowpack/plugin-dotenv',
    '@snowpack/plugin-typescript',
    [
      '@snowpack/plugin-webpack',
      {
        extendConfig: modifyWebpackConfig
      }
    ],
  ],
  routes: [
    /* Enable an SPA Fallback in development: */
    // {"match": "routes", "src": ".*", "dest": "/index.html"},
  ],
  optimize: {
    /* Example: Bundle your final build: */
    // "bundle": true,
  },
  packageOptions: {
    /* ... */
  },
  devOptions: {
    /* ... */
  },
  buildOptions: {
    /* ... */
  },
};
